### ISSUE TITLE
Crash upon trying to use the tile paint tool

### ISSUE THREAD

**Issue by Sos339** [CyberZHG/Terraria-Map-Editor#1]
08-06-2015 18:02: Starting TEdit 3.5.15218.1802 
08-06-2015 18:02: OS: Microsoft Windows NT 6.1.7601 Service Pack 1 
08-06-2015 18:02: .Net >= 4.0 
08-06-2015 18:02: XNA 4.0 
08-06-2015 18:02: Terraria Data Path: E:\Programs\Steam\steamapps\common\Terraria\Content 
08-06-2015 18:02: Creating Undo cache: C:\Users\Josh\AppData\Roaming\TEdit\undo_674868617 
08-06-2015 18:02: Error - Exception of type 'System.OutOfMemoryException' was thrown.
   at TEditXna.Editor.Tools.BrushTool.MouseDown(TileMouseState e) in e:\Terraria stuff\Tedit 2\Tedit 1.3\Terraria-Map-Editor-master\TEditXna\Editor\Tools\BrushTool.cs:line 34
   at TEditXna.ViewModel.WorldViewModel.MouseDownTile(TileMouseState e) in e:\Terraria stuff\Tedit 2\Tedit 1.3\Terraria-Map-Editor-master\TEditXna\ViewModel\WorldViewModel.cs:line 657
   at TEditXna.View.WorldRenderXna.xnaViewport_HwndLButtonDown(Object sender, HwndMouseEventArgs e) in e:\Terraria stuff\Tedit 2\Tedit 1.3\Terraria-Map-Editor-master\TEditXna\View\WorldRenderXna.xaml.cs:line 1601
   at TEdit.UI.Xaml.XnaContentHost.GraphicsDeviceControl.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) in e:\Terraria stuff\Tedit 2\Tedit 1.3\Terraria-Map-Editor-master\TEditXna\UI\Xaml\XnaContentHost\GraphicsDeviceControl.cs:line 482
   at System.Windows.Interop.HwndHost.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at TEditXna.App.Main() in e:\Terraria stuff\Tedit 2\Tedit 1.3\Terraria-Map-Editor-master\TEditXna\obj\x86\Release\App.g.cs:line 0

**Comment by CyberZHG** [comment]
Probably the same issue: [Issue 632](https://github.com/TEdit/Terraria-Map-Editor/issues/632)
Try this binary: [55a2c97](https://drive.google.com/file/d/0BzGgvgeRcwOYejZYNm9xbWdOajQ/view?usp=sharing)

**Comment by Sos339** [comment]
Thanks that appeared to fix the issue
